version: "3"

services:
    node-red:
        container_name: nodered
        build: ./nodered/.
        restart: unless-stopped
        ports: 
            - "1880:1880"
        environment:
            - TZ=Etc/UTC
        volumes:
            - node-red-data:/data
    influxdb:
        container_name: influxdb
        image: "influxdb:1.8"
        restart: unless-stopped
        ports: 
            - "8086:8086"

        environment:
            - TZ=Etc/UTC
            - INFLUXDB_HTTP_FLUX_ENABLED=false
            - INFLUXDB_REPORTING_DISABLED=false
            - INFLUXDB_HTTP_AUTH_ENABLED=false
            - INFLUXDB_MONITOR_STORE_ENABLED=false
            - INFLUXDB_DB=BatteryMonitor

        volumes:
            - influxdb-storage:/var/lib/influxdb

    grafana:
        image: grafana/grafana:latest
        ports:
            - '3000:3000'
        volumes:
            - grafana-storage:/var/lib/grafana
            - ./grafana/:/etc/grafana/provisioning
        depends_on:
            - influxdb
        environment:
            - GF_SECURITY_ADMIN_USER=admin
            - GF_SECURITY_ADMIN_PASSWORD=admin
            

volumes: 
    node-red-data: 
    influxdb-storage:
    grafana-storage:

